<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Resit.Modules.Bills.Application\Resit.Modules.Bills.Application.csproj" />
    <ProjectReference Include="..\Resit.Modules.Bills.Infrastructure\Resit.Modules.Bills.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Identity\Resit.Modules.Identity\Resit.Modules.Identity.csproj" />
  </ItemGroup>
</Project>
