<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Resit.Modules.Bills.Domain\Resit.Modules.Bills.Domain.csproj" />
    <ProjectReference Include="..\..\Notifications\Resit.Modules.Notifications\Resit.Modules.Notifications.csproj" />
  </ItemGroup>
</Project>
